accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.contrib.auth.decorators import user_passes_test
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from .forms import UserLoginForm, PwdResetForm, PwdChangeForm, PwdResetForm, PwdResetConfirmForm

app_name = 'accounts'

urlpatterns = [
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name="registration/password_change_form.html",
                                                                   form_class=PwdChangeForm), name='pwdforgot'),
    path('login/', auth_views.LoginView.as_view(template_name="registration/login.html",
                                                authentication_form=UserLoginForm), name='login'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="registration/password_reset_form.html",
                                                                 form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html', form_class=PwdResetConfirmForm), name="pwdresetconfirm"),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.edit, name='edit'),
    path('fav/<int:id>/', views.favourite_add, name='favourite_add'),
    path('profile/favourites/', views.favourite_list, name='favourite_list'),
    path('like/', views.like, name='like'),
    path('profile/delete/', views.delete_user, name='deleteuser'),
    path('register/', views.accounts_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>)/',
         views.activate, name='activate'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='homepage'),
    path('search/', views.post_search, name='post_search'),
    path('<slug:post>/', views.post_single, name='post_single'),
    path('category/<category>/', views.CatListView.as_view(), name='category'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('account/', include('django.contrib.auth.urls')),
    path('', include('blog.urls', namespace='blog')),
    path('services/', include('services.urls', namespace='services')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.core.exceptions import ValidationError
from django.core.files.images import get_image_dimensions


def user_directory_path(instance, filename):
    return 'users/avatars/{0}/{1}'.format(instance.user.id, filename)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(
        upload_to=user_directory_path, default='users/avatar.jpg')
    bio = models.TextField(max_length=500, blank=True)

    def clean(self):
        if not self.avatar:
            raise ValidationError("x")
        else:
            w, h = get_image_dimensions(self.avatar)
            if w != 200:
                raise ValidationError("x")
            if h != 200:
                raise ValidationError("x")

    def __str__(self):
        return self.user.username


@ receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import AuthenticationForm, PasswordResetForm, PasswordChangeForm, SetPasswordForm
from accounts.models import Profile

# https://docs.djangoproject.com/en/3.0/topics/auth/default/
# https://docs.djangoproject.com/en/3.0/topics/forms/


class PwdResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label='New password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'form-newpass'}))
    new_password2 = forms.CharField(
        label='Repeat password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'form-new-pass2'}))


class UserLoginForm(AuthenticationForm):

    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control mb-3', 'placeholder': 'Username', 'id': 'login-username'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Password',
            'id': 'login-pwd',
        }
    ))


class PwdChangeForm(PasswordChangeForm):

    old_password = forms.CharField(
        label='Old Password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'Old Password', 'id': 'form-oldpass'}))
    new_password1 = forms.CharField(
        label='New password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'form-newpass'}))
    new_password2 = forms.CharField(
        label='Repeat password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'form-new-pass2'}))


class PwdResetForm(PasswordResetForm):

    email = forms.EmailField(max_length=254, widget=forms.TextInput(
        attrs={'class': 'form-control mb-3', 'placeholder': 'Email', 'id': 'form-email'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        test = User.objects.filter(email=email)
        if not test:
            raise forms.ValidationError(
                'Unfortunatley we can not find that email address')
        return email


class RegistrationForm(forms.ModelForm):

    username = forms.CharField(
        label='Enter Username', min_length=4, max_length=50, help_text='Required')
    email = forms.EmailField(max_length=100, help_text='Required', error_messages={
        'required': 'Sorry, you will need an email'})
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name',)

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise ValidationError("Username already exists")
        return username

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords do not match.')
        return cd['password2']

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(
                'Please use another Email, that is already taken')
        return email

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Username'})
        self.fields['email'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'E-mail', 'name': 'email', 'id': 'id_email'})
        self.fields['password'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Password'})
        self.fields['password2'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Repeat Password'})


class UserEditForm(forms.ModelForm):

    first_name = forms.CharField(
        label='Firstname', min_length=4, max_length=50, widget=forms.TextInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'Firstname', 'id': 'form-firstname'}))

    last_name = forms.CharField(
        label='Lastname', min_length=4, max_length=50, widget=forms.TextInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'Lastname', 'id': 'form-lastname'}))

    email = forms.EmailField(
        max_length=200, widget=forms.TextInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'Old Password', 'id': 'form-email'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['last_name'].required = False
        self.fields['email'].required = False


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['bio', 'avatar']

        widgets = {
            'bio': forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}),
        }

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth.models import User
from .forms import RegistrationForm, UserEditForm, UserProfileForm
from .tokens import account_activation_token
from .models import Profile
from blog.models import Post
from django.http import JsonResponse


@ login_required
def like(request):
    if request.POST.get('action') == 'post':
        result = ''
        id = int(request.POST.get('postid'))
        post = get_object_or_404(Post, id=id)
        if post.likes.filter(id=request.user.id).exists():
            post.likes.remove(request.user)
            post.like_count -= 1
            result = post.like_count
            post.save()
        else:
            post.likes.add(request.user)
            post.like_count += 1
            result = post.like_count
            post.save()

        return JsonResponse({'result': result, })


@ login_required
def favourite_list(request):
    new = Post.newmanager.filter(favourites=request.user)
    return render(request,
                  'accounts/favourites.html',
                  {'new': new})


@ login_required
def favourite_add(request, id):
    post = get_object_or_404(Post, id=id)
    if post.favourites.filter(id=request.user.id).exists():
        post.favourites.remove(request.user)
    else:
        post.favourites.add(request.user)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def avatar(request):
    if request.user.is_authenticated:
        user = User.objects.get(username=request.user)
        avatar = Profile.objects.filter(user=user)
        context = {
            "avatar": avatar,
        }
        return context
    else:
        return {
            'NotLoggedIn': User.objects.none()
        }


@login_required
def profile(request):
    return render(request,
                  'accounts/profile.html',
                  {'section': 'profile'})


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)

        profile_form = UserProfileForm(
            request.POST, request.FILES, instance=request.user.profile)

        if profile_form.is_valid() and user_form.is_valid():
            user_form.save()
            profile_form.save()
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = UserProfileForm(instance=request.user.profile)

    return render(request,
                  'accounts/update.html',
                  {'user_form': user_form, 'profile_form': profile_form})


@login_required
def delete_user(request):

    if request.method == 'POST':
        user = User.objects.get(username=request.user)
        user.is_active = False
        user.save()
        return redirect('accounts:login')

    return render(request, 'accounts/delete.html')


def post_search(request):
    form = PostSearchForm()
    q = ''
    c = ''
    results = []
    query = Q()

    if 'q' in request.GET:
        form = PostSearchForm(request.GET)
        if form.is_valid():
            q = form.cleaned_data['q']
            c = form.cleaned_data['c']

            if c is not None:
                query &= Q(category=c)
            if q is not None:
                query &= Q(title__contains=q)

            results = Post.objects.filter(query)

    return render(request, 'blog/search.html',
                  {'form': form,
                   'q': q,
                   'results': results})


def accounts_register(request):
    if request.method == 'POST':
        registerForm = RegistrationForm(request.POST)
        if registerForm.is_valid():
            user = registerForm.save(commit=False)
            user.email = registerForm.cleaned_data['email']
            user.set_password(registerForm.cleaned_data['password'])
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            subject = 'Activate your Account'
            message = render_to_string('registration/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject=subject, message=message)
            return HttpResponse('registered succesfully and activation sent')
    else:
        registerForm = RegistrationForm()
    return render(request, 'registration/register.html', {'form': registerForm})


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return redirect('login')
    else:
        return render(request, 'registration/activation_invalid.html')

templates/accounts/delete.html
{% extends "../base/base.html" %}
{% block title %}Profile{% endblock %}
{% block content %}

<div class="container-fluid my-5">
    <section class="px-md-5 mx-md-5 text-center text-lg-left dark-grey-text">
        <div class="row d-flex justify-content-center">
            <div class="col-md-6">
                <form class="form-reset p-4 rounded update-form" action="{% url "accounts:deleteuser" %}" method="post">
                    {% csrf_token %}
                    <p class=" h5 mb-2 pt-4 font-weight-bold">Delete Account</p>
                    <p>Are you sure you want to delete your account?
                        *Important - your account data will remain available for 20 days</p>
                    <button type="submit" role="button"
                        class="btn btn-danger btn-block py-2 mb-4 mt-5 font-weight-bold">Delete</button>
                </form>
                <p class="small text-center pt-4">
                    <a href="{% url "accounts:profile" %}">Back to Dashboard</a>
                </p>
                <p class="small text-center">
                    <a href="{% url "accounts:register" %}">Help Center?</a>
                </p>
            </div>
        </div>
    </section>
</div>
{% endblock %}

templates/accounts/favourites.html
{% extends "../base/base.html" %}
{% block title %}Users Favourties{% endblock %}
{% block content %}
{% include "../base/nav-main.html" %}
<div class="container">
    <section class="jumbotron text-center bg-white">
        <div class="container">
            <h1>Users saved favourite posts</h1>
            <p class="lead text-muted">Here you can remove or view the favourites posts you have added</p>
        </div>
    </section>
    <div>
        <div class="row">
            {% for post in new %}
            <div class="col-md-4">
                <a class="text-dark" href="{{post.get_absolute_url}}">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" src="{{post.image.url}}" alt="{{ post.title }}">
                        <div class="card-body">
                            <h2 style="font-size:18px;font-weight:bold">{{post.title|truncatechars:50}}</h2>
                            <p class="card-text">{{post.excerpt|truncatechars:50}}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-muted">9 mins</small>
                                <div id="favourite-section"><a href="{% url 'accounts:favourite_add' post.id %}"
                                        class="btn btn-outline-primary">Remove</a></div>
                            </div>

                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% include "base/footer.html" %}
{% endblock %}

templates/accounts/profile.html
{% extends "../base/base.html" %}
{% block title %}Profile{% endblock %}
{% block content %}
{% include "../base/nav-main.html" %}
<div class="container">
    <section class="jumbotron text-center bg-white">
        <div class="container">
            <h1>User Dashboard</h1>
            <p class="lead text-muted">Something short and leading about the collection below—its contents, the
                creator,
                etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
            <p>
                <a href="#" class="btn btn-primary my-2">Logout</a>
            </p>
        </div>
    </section>
</div>
{% include "base/footer.html" %}
{% endblock %}

templates/accounts/update.html
{% extends "../base/base.html" %}
{% block title %}Edit your account{% endblock %}
{% block content %}
{% include "base/nav-main.html" %}
<style>
    .update-form input {
        border: 2px solid #ccc;
        height: calc(2em + .75rem + 2px);
    }

    .update-form input:focus {
        border-color: #1497ff;
        box-shadow: inset 0 0px 0px rgba(0, 0, 0, 0.075), 0 0 0px rgba(255, 0, 0, 0.6);
    }
</style>

<div class="container-fluid my-5">
    <section class="px-md-5 mx-md-5 text-center text-lg-left dark-grey-text">
        <div class="row d-flex justify-content-center">
            <div class="col-md-6">

                <form class="form-reset p-4 rounded update-form" method="post" enctype="multipart/form-data">

                    {% if user_form.is_valid and profile_form.is_valid  %}
                    <div class="alert alert-primary" role="alert">
                        Details successfully updated!
                    </div>
                    <p class="small text-center pt-0">
                        <a href="{% url "accounts:profile" %}">Back to Dashboard</a>
                    </p>
                    {%else%}
                    <p class=" h4 mb-4 font-weight-bold">Change your details</p>
                    <p>You can edit your account using the following form:</p>
                    {% endif %}

                    {% if form.errors %}
                    <div class="alert alert-primary" role="alert">
                        Error: Please try again!
                    </div>
                    {% endif %}

                    {% if profile_form.errors %}
                    <div class="alert alert-primary" role="alert">
                        Error: Filesize incorrect - has to be 100px by 100px
                    </div>
                    {% endif %}

                    {% csrf_token %}
                    <label class="small font-weight-bold">{{ user_form.first_name.label}}</label>
                    {{ user_form.first_name }}
                    <label class="small font-weight-bold">{{ user_form.last_name.label}}</label>
                    {{ user_form.last_name }}
                    <label class="small font-weight-bold">{{ user_form.email.label}}</label>
                    {{ user_form.email }}


                    <label class="small font-weight-bold">{{ profile_form.bio.label}}</label>
                    {{ profile_form.bio }}

                    <div class="form-group pt-5">
                        <label class="small font-weight-bold">{{ profile_form.avatar.label}}</label>
                        {{ profile_form.avatar}}
                    </div>


                    <button class="btn btn-primary btn-block py-2 mb-4 mt-5 font-weight-bold" type="submit"
                        value="Save changes">Save Changes</button>
                    <hr class="mb-3">
                    <p class=" h5 mb-2 pt-4 font-weight-bold">Delete Account</p>
                    <p class="small">If you would like to delete your account press the button below:</p>
                    <a href="{% url "accounts:deleteuser" %}"
                        class="btn btn-danger btn-block py-2 mb-4 mt-5 font-weight-bold" role="button"
                        aria-pressed="true">Delete Account</a>
                </form>

            </div>
        </div>
    </section>
</div>
{% include "base/footer.html" %}
{% endblock %}