accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.contrib.auth.decorators import user_passes_test
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from .forms import UserLoginForm, PwdResetForm, PwdChangeForm, PwdResetForm, PwdResetConfirmForm

app_name = 'accounts'

urlpatterns = [
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name="registration/password_change_form.html",
                                                                   form_class=PwdChangeForm), name='pwdforgot'),
    path('login/', auth_views.LoginView.as_view(template_name="registration/login.html",
                                                authentication_form=UserLoginForm), name='login'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="registration/password_reset_form.html",
                                                                 form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html', form_class=PwdResetConfirmForm), name="pwdresetconfirm"),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.edit, name='edit'),
    path('fav/<int:id>/', views.favourite_add, name='favourite_add'),
    path('profile/favourites/', views.favourite_list, name='favourite_list'),
    path('like/', views.like, name='like'),
    path('profile/delete/', views.delete_user, name='deleteuser'),
    path('register/', views.accounts_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>)/',
         views.activate, name='activate'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='homepage'),
    path('search/', views.post_search, name='post_search'),
    path('<slug:post>/', views.post_single, name='post_single'),
    path('category/<category>/', views.CatListView.as_view(), name='category'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('account/', include('django.contrib.auth.urls')),
    path('', include('blog.urls', namespace='blog')),
    path('services/', include('services.urls', namespace='services')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey


def user_directory_path(instance, filename):
    return 'posts/%Y/%m/%d/'.format(instance.id, filename)


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):

    class NewManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset() .filter(status='published')

    options = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT, default=1)
    title = models.CharField(max_length=250)
    excerpt = models.TextField(null=True)
    image = models.ImageField(
        upload_to=user_directory_path, default='posts/default.jpg')
    image_caption = models.CharField(max_length=100, default='Photo by Blog')
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    publish = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts')
    content = models.TextField()
    status = models.CharField(max_length=10, choices=options, default='draft')
    favourites = models.ManyToManyField(
        User, related_name='favourite', default=None, blank=True)
    likes = models.ManyToManyField(
        User, related_name='like', default=None, blank=True)
    like_count = models.BigIntegerField(default='0')
    objects = models.Manager()  # default manager
    newmanager = NewManager()  # custom manager

    def get_absolute_url(self):
        return reverse('blog:post_single', args=[self.slug])

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title


class Comment(MPTTModel):

    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=50)
    parent = TreeForeignKey('self', on_delete=models.CASCADE,
                            null=True, blank=True, related_name='children')
    email = models.EmailField()
    content = models.TextField()
    publish = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)

    class MPTTMeta:
        order_insertion_by = ['publish']

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from .models import Comment, Category
from mptt.forms import TreeNodeChoiceField


class NewCommentForm(forms.ModelForm):
    parent = TreeNodeChoiceField(queryset=Comment.objects.all())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['parent'].widget.attrs.update(
            {'class': 'd-none'})
        self.fields['parent'].label = ''
        self.fields['parent'].required = False

    class Meta:
        model = Comment
        fields = ('name', 'parent', 'email', 'content')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'col-sm-12'}),
            'email': forms.TextInput(attrs={'class': 'col-sm-12'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
        }

    def save(self, *args, **kwargs):
        Comment.objects.rebuild()
        return super(NewCommentForm, self).save(*args, **kwargs)


class PostSearchForm(forms.Form):
    q = forms.CharField()
    c = forms.ModelChoiceField(
        queryset=Category.objects.all().order_by('name'))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['c'].label = ''
        self.fields['c'].required = False
        self.fields['c'].label = 'Category'
        self.fields['q'].label = 'Search For'
        self.fields['q'].widget.attrs.update(
            {'class': 'form-control'})

blog/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from .models import Post, Comment, Category
from .forms import NewCommentForm, PostSearchForm
from django.views.generic import ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q


def home(request):

    all_posts = Post.newmanager.all()

    return render(request, 'blog/index.html', {'posts': all_posts})


def post_single(request, post):

    post = get_object_or_404(Post, slug=post, status='published')

    fav = bool

    if post.favourites.filter(id=request.user.id).exists():
        fav = True

    allcomments = post.comments.filter(status=True)
    page = request.GET.get('page', 1)

    paginator = Paginator(allcomments, 10)
    try:
        comments = paginator.page(page)
    except PageNotAnInteger:
        comments = paginator.page(1)
    except EmptyPage:
        comments = paginator.page(paginator.num_pages)

    user_comment = None

    if request.method == 'POST':
        comment_form = NewCommentForm(request.POST)
        if comment_form.is_valid():
            user_comment = comment_form.save(commit=False)
            user_comment.post = post
            user_comment.save()
            return HttpResponseRedirect('/' + post.slug)
    else:
        comment_form = NewCommentForm()
    return render(request, 'blog/single.html', {'post': post, 'comments':  user_comment, 'comments': comments, 'comment_form': comment_form, 'allcomments': allcomments, 'fav': fav})


class CatListView(ListView):
    template_name = 'blog/category.html'
    context_object_name = 'catlist'

    def get_queryset(self):
        content = {
            'cat': self.kwargs['category'],
            'posts': Post.objects.filter(category__name=self.kwargs['category']).filter(status='published')
        }
        return content


def category_list(request):
    category_list = Category.objects.exclude(name='default')
    context = {
        "category_list": category_list,
    }
    return context


def post_search(request):
    form = PostSearchForm()
    q = ''
    c = ''
    results = []
    query = Q()

    if 'q' in request.GET:
        form = PostSearchForm(request.GET)
        if form.is_valid():
            q = form.cleaned_data['q']
            c = form.cleaned_data['c']

            if c is not None:
                query &= Q(category=c)
            if q is not None:
                query &= Q(title__contains=q)

            results = Post.objects.filter(query)

    return render(request, 'blog/search.html',
                  {'form': form,
                   'q': q,
                   'results': results})

templates/blog/category.html
    {% extends "../base/base.html" %}

    {% block title %}
    Catlist
    {% endblock %}

    {% block content %}
    {% include "base/nav-main.html" %}
    <div class="album py-5 bg-light">
      <div class="container">
        <div class="row">
          <div class="col-12 pb-5">
            <h1> List of {{catlist.cat}} posts</h1>
          </div>
          {% for post in catlist.posts %}
          <div class="col-md-4">
            <a class="text-dark" href="{{post.get_absolute_url}}">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" src="{{post.image.url}}" alt="{{ post.title }}">
                <div class="card-body">
                  <h2 style="font-size:18px;font-weight:bold">{{post.title|truncatechars:50}}</h2>
                  <p class="card-text">{{post.excerpt|truncatechars:50}}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
            </a>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>

    {% endblock %}

templates/blog/index.html
    {% extends "../base/base.html" %}
    {% block title %}
    Welcome to Blog
    {% endblock %}
    {% block content %}
    {% include "base/nav-main.html" %}
    <div class="container">
      <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Tutorials</h1>
        <p class="lead">Quickly build an effective pricing table for your potential customers with this Bootstrap
          example.
          It’s built with default Bootstrap components and utilities with little customization.</p>
      </div>
      <div class="py-5">
        <div class="row">
          {% for post in posts %}
          <div class="col-md-4">
            <a class="text-dark" href="{{post.get_absolute_url}}">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" src="{{post.image.url}}" alt="{{ post.title }}">
                <div class="card-body">
                  <h2 style="font-size:18px;font-weight:bold">{{post.title|truncatechars:50}}</h2>
                  <p class="card-text">{{post.excerpt|truncatechars:50}}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
            </a>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
    {% include "base/footer.html" %}
    {% endblock %}

templates/blog/search.html
{% extends "../base/base.html" %}
{% block title %}Search Page{% endblock %}
{% block content %}
{% include "base/nav-main.html" %}
<div class="container pt-5">
    {% if q %}
    <h1>Posts containing "{{ q }}"
        {% if c %}
        In category "{{ c }}"
        {% endif %}
    </h1>
    <p>
        {% with results.count as total_results %}
        Found {{ total_results }} result{{ total_results|pluralize }}
        {% endwith %}
    </p>
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                {% for post in results %}
                <div class="col-md-4">
                    <a class="text-dark" href="{{post.get_absolute_url}}">
                        <div class="card mb-4 box-shadow">
                            <img class="card-img-top" src="{{post.image.url}}" alt="{{ post.title }}">
                            <div class="card-body">
                                <h2 style="font-size:18px;font-weight:bold">{{post.title|truncatechars:50}}</h2>
                                <p class="card-text">{{post.excerpt|truncatechars:50}}</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <small class="text-muted">9 mins</small>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                {% empty %}
                <p>There are no results for your query.</p>
                {% endfor %}
            </div>
        </div>
    </div>
    <p><a href="{% url "blog:post_search" %}" class="btn btn-primary" role="button" aria-disabled="true">New
            Search</a>
    </p>
    {% else %}
    <h1>Search for posts</h1>
    <form method="get">
        {{ form.as_p }}
        <input class="btn btn-primary my-1" type="submit" value="Search">
    </form>
    {% endif %}
</div>
{% endblock %}

templates/blog/single.html
{% extends "../base/base.html" %}

{% block title %}
{{post.title}}
{% endblock %}

{% block content %}
{% include "base/nav-main.html" %}

<style>
  @import url('https://fonts.googleapis.com/css2?family=DM+Serif+Display&display=swap');
  @import url('https://fonts.googleapis.com/css2?family=PT+Serif:wght@400;700&display=swap');

  .h1 {
    font-family: 'PT Serif', serif;
    font-size: 2.55rem;
    line-height: 2.6rem;
    letter-spacing: -0.063px;
  }

  h2 {
    font-family: 'PT Serif', serif;
    font-size: 1.9rem;
    line-height: 2.6rem;
    letter-spacing: -0.063px;
    font-weight: 700;
    padding-top: 48px;
  }

  p {
    font-family: 'PT Serif', serif;
    line-height: 2rem;
    font-size: 1.3rem
  }

  @media screen and (min-width: 600px) {
    .children form {
      margin-left: -48px;
      /* will touch very left side */
    }

    .children .children form {
      margin-left: -96px;
      /* will touch very left side */
    }
  }

  .avatar_single {
    height: 48px;
    width: 48px;
    background-color: #000;
    border-radius: 50%;
    display: inline-block;

  }

  .smaller {
    font-size: 0.8rem;
  }
</style>

<div class="container">
  <div class="row justify-content-md-center pt-5">
    <div class="col-md-8 d-flex justify-content-between">
      <h1 class="h1">{{post.title}}</h1>
    </div>
    <div class="col-md-8 d-flex justify-content-between pt-3">
      <div class="d-flex">
        <div><img class="avatar_single" src="{{ post.author.profile.avatar.url }}"></div>
        <div class="pl-3 no-gutters">
          <div class="col-12 no-gutters">{{ post.author|title }}</div>
          <div class="col-12 no-gutters smaller text-muted">{{post.publish}}</div>
        </div>
      </div>
      <div class="d-flex">
        {% if request.user.is_authenticated %}
        <div class="pr-2">
          <span class="" id="like_count">{{post.like_count}}</span>
          <button class="btn btn-link text-dark p-0 border-0 btn-outline-light" id="like-button" value="{{post.id}}">
            <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-heart" fill="currentColor"
              xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd"
                d="M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z" />
            </svg>
          </button>
        </div>
        {% if fav %}
        <div>
          <a href="{% url 'accounts:favourite_list' %}" class="text-dark">
            <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-bookmark-check" fill="currentColor"
              xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd"
                d="M4.5 2a.5.5 0 0 0-.5.5v11.066l4-2.667 4 2.667V8.5a.5.5 0 0 1 1 0v6.934l-5-3.333-5 3.333V2.5A1.5 1.5 0 0 1 4.5 1h4a.5.5 0 0 1 0 1h-4z" />
              <path fill-rule="evenodd"
                d="M15.854 2.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 .708-.708L12.5 4.793l2.646-2.647a.5.5 0 0 1 .708 0z" />
            </svg>
          </a>
        </div>
        {% else %}
        <div>
          <a href="{% url 'accounts:favourite_add' post.id %}" class="text-dark">
            <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-bookmark-plus" fill="currentColor"
              xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd"
                d="M4.5 2a.5.5 0 0 0-.5.5v11.066l4-2.667 4 2.667V8.5a.5.5 0 0 1 1 0v6.934l-5-3.333-5 3.333V2.5A1.5 1.5 0 0 1 4.5 1h4a.5.5 0 0 1 0 1h-4zm9-1a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1H13V1.5a.5.5 0 0 1 .5-.5z" />
              <path fill-rule="evenodd" d="M13 3.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0v-2z" />
            </svg>
          </a>
        </div>
        {% endif %}
        {% else %}
        <div class="pr-2">
          <span class="" id="like_count">{{post.like_count}}</span>
          <a href="{% url 'accounts:register' %}" class="btn btn-link text-dark p-0 border-0 btn-outline-light"
            value="{{post.id}}">
            <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-heart" fill="currentColor"
              xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd"
                d="M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z" />
            </svg>
          </a>
        </div>
        <div>
          <a href="{% url 'accounts:register' %}" class="text-dark"> <svg width="1.5em" height="1.5em"
              viewBox="0 0 16 16" class="bi bi-bookmark-plus" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd"
                d="M4.5 2a.5.5 0 0 0-.5.5v11.066l4-2.667 4 2.667V8.5a.5.5 0 0 1 1 0v6.934l-5-3.333-5 3.333V2.5A1.5 1.5 0 0 1 4.5 1h4a.5.5 0 0 1 0 1h-4zm9-1a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1H13V1.5a.5.5 0 0 1 .5-.5z" />
              <path fill-rule="evenodd" d="M13 3.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0v-2z" />
            </svg></a>
        </div>
        {% endif %}
      </div>
    </div>
    <div class="col-md-8 pt-5">
      <img class="card-img-top" src="{{post.image.url}}" alt="{{ post.title }}">
      <div class="col-12 text-center small text-muted pt-1">{{post.image_caption}}</div>
      <p>{{post.content|safe}}</p>
    </div>
    <div class="col-md-8">
      {% with allcomments.count as total_comments %}
      <h2>
        {{ total_comments }} comment{{ total_comments|pluralize }}
      </h2>
      {% endwith %}
      {% load mptt_tags %}
      <div>
        {% recursetree comments %}
        <div id="{{ node.id }}" class="my-2 p-2" style="border: 1px solid grey">
          <div class="d-flex justify-content-between">By {{ node.name }}<div></div>{{ node.publish }}</div>
          <div>{{ node.content }}</div>
          <hr />
          {% if node.level < 3 %}
          <button class="button" onclick="myFunction({{ node.id }})">Reply</button>
          {% endif %}
        </div>
        {% if not node.is_leaf_node %}
        <div class="children pl-2 pl-md-5">
          {{ children }}
        </div>
        {% endif %}
        {% endrecursetree %}
      </div>
      <nav aria-label="Page navigation example">
        {% if comments.has_other_pages %}
        <ul class="pagination">
          {% if comments.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ comments.previous_page_number }}">Previous</a>
          </li>
          {% else %}
          <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
          {% endif %}
          {% for num in comments.paginator.page_range %}
          {% if comments.number == l %}
          <li class="page-item active"><span class="page-link">{{ num }} <span class="sr-only">(current)</span></span>
          </li>
          {% else %}
          <li><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
          {% endif %}
          {% endfor %}
          {% if comments.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ comments.next_page_number }}">Next</a></li>
          {% else %}
          <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
          {% endif %}
        </ul>
        {% endif %}
      </nav>
      <form id="myForm" method="post">
        <h2>Create new comment</h2>
        {{ comment_form.as_p }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
      </form>
    </div>
  </div>
</div>

<script>
  function formExit() {
    document.getElementById("newForm").remove();
  }

  function myFunction(id) {
    if (document.contains(document.getElementById("newForm"))) {
      document.getElementById("newForm").remove();
    }

    var d1 = document.getElementById(id);
    d1.insertAdjacentHTML('afterend',
      '<form id="newForm" class="form-insert py-2" method="post"> \
                <div class="d-flex justify-content-between"><h2>Reply:</h2><div><button type="button" class="btn btn-outline-secondary" onclick="formExit()"">Close</button></div></div> \
                <label for="id_name">Name:</label> \
                <input type="text" name="name" class="col-sm-12" maxlength="50" required="" id="id_name">\
                <select name="parent" class="d-none" id="id_parentt"> \
                <option value="' + id + '" selected="' + id + '"></option> \
                </select> \
                <label for="id_email">Email:</label> \
                <input type="text" name="email" class="col-sm-12" maxlength="254" required="" id="id_email"> \
                <label for="id_content">Content:</label> \
                <textarea name="content" cols="40" rows="5" class="form-control" required id="id_content"></textarea> \
                {% csrf_token %} \
                <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button> \
              </form>');
  }

  $('#myForm').trigger("reset");

  $(document).on('click', '#like-button', function (e) {
    e.preventDefault();
    $.ajax({
      type: 'POST',
      url: '{% url "accounts:like" %}',
      data: {
        postid: $('#like-button').val(),
        csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
        action: 'post'
      },
      success: function (json) {
        document.getElementById("like_count").innerHTML = json['result']
      },
      error: function (xhr, errmsg, err) {

      }
    });
  })
</script>

{% include "base/footer.html" %}
{% endblock %}